SELECT FIRST_NAME AS WORKER_NAME
FROM Worker;

SELECT UPPER(FIRST_NAME)
FROM Worker;

SELECT DISTINCT DEPARTMENT
FROM Worker;

SELECT SUBSTRING(FIRST_NAME,1,3)
FROM Worker;

SELECT CHARINDEX('a','Amitabh');

SELECT RTRIM(FIRST_NAME)
FROM Worker;

SELECT LTRIM(DEPARTMENT)
FROM Worker;

SELECT DISTINCT DEPARTMENT, LEN(DEPARTMENT)
FROM Worker;

SELECT REPLACE(FIRST_NAME,'a','A')
FROM Worker;

SELECT FIRST_NAME + ' ' + LAST_NAME AS COMPLETE_NAME
FROM Worker;

SELECT *
FROM Worker
ORDER BY FIRST_NAME ASC;

SELECT *
FROM Worker
ORDER BY FIRST_NAME ASC, DEPARTMENT DESC;

SELECT *
FROM Worker
WHERE FIRST_NAME IN ('Vipul','Satish');

SELECT *
FROM Worker
WHERE FIRST_NAME NOT IN ('Vipul','Satish');

SELECT *
FROM Worker
WHERE DEPARTMENT='Admin';

SELECT *
FROM Worker
WHERE FIRST_NAME LIKE '%a%';

SELECT *
FROM Worker
WHERE FIRST_NAME LIKE '%a';

SELECT *
FROM Worker
WHERE FIRST_NAME LIKE '_____h';

SELECT *
FROM Worker
WHERE SALARY BETWEEN 100000 AND 500000;

SELECT *
FROM Worker
WHERE MONTH(JOINING_DATE)=2
AND YEAR(JOINING_DATE)=2014;

SELECT FIRST_NAME, SALARY
FROM Worker
WHERE SALARY BETWEEN 50000 AND 100000;

SELECT DEPARTMENT, COUNT(*) AS TOTAL_WORKERS
FROM Worker
GROUP BY DEPARTMENT
ORDER BY TOTAL_WORKERS DESC;

SELECT W.*
FROM Worker W
JOIN Title T
ON W.WORKER_ID = T.WORKER_REF_ID
WHERE T.WORKER_TITLE = 'Manager';

SELECT GETDATE();

SELECT TOP 10 *
FROM Worker;